INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'TBSラジオ「見事なお仕事」で #rebuildfm が紹介された', 'https://twitter.com/miyagawa/status/1256502711853256704');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'Zoom飲みで遊ぶ「オンライン人狼」', 'https://japanese.engadget.com/jp-2020-04-21-zoom.html');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'レインボー コントチャンネル - YouTube', 'https://www.youtube.com/channel/UC9UI_fNxTbfEJImAg5Y7pOw');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, '短編映画『カメラを止めるな！リモート大作戦！』本編', 'https://www.youtube.com/watch?v=HTk2wqBxVfY&feature=youtu.be');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'Tiger King', 'https://www.netflix.com/title/81115994');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'The Jinx: The Life and Deaths of Robert Durst', 'https://www.hbo.com/the-jinx-the-life-and-deaths-of-robert-durst');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'Making A Murderer', 'https://www.netflix.com/title/80000770');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'The Staircase', 'https://www.netflix.com/title/80233441');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'Serial', 'https://serialpodcast.org/');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, '殺人犯はそこにいる―隠蔽された北関東連続幼女誘拐殺人事件', 'https://www.amazon.co.jp/dp/B01M3XWO1W/?tag=bulknews-22');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'Apple and Google release sample code, UI and detailed policies for COVID-19 exposure-notification apps', 'https://techcrunch.com/2020/05/04/apple-and-google-release-sample-code-and-detailed-policies-for-covid-19-exposure-notification-apps/');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'Newsom says reopening California will begin Friday amid coronavirus', 'https://www.latimes.com/california/story/2020-05-04/california-reopening-coronavirus-gavin-newsom-phases-begin-retail-pickup');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'Trump unveils federal guidelines for reopening country', 'https://www.mercurynews.com/2020/04/16/trump-unveils-federal-guidelines-for-reopening-country/');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'Anderson Cooper presses Las Vegas mayor over wish to reopen', 'https://www.cnn.com/videos/politics/2020/04/22/las-vegas-mayor-carolyn-goodman-reopen-coronavirus-entire-interview-anderson-cooper-sot-nr-vpx.cnn');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'Coronavirus, Explained', 'https://www.netflix.com/title/81273378');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, '豆腐の容器を開けるのに悪戦苦闘する星野源さん', 'https://twitter.com/jt_dunk/status/1256024358587207680');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'なかなかUSBがさせない星野源', 'https://mobile.twitter.com/Nakajima_IT_bot/status/1256363105900130305');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'Apple Considers a Face ID Workaround for Users Wearing Masks', 'https://www.wired.com/story/apple-considers-a-face-id-workaround-for-users-wearing-masks/');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'BILINGUALNEWS | バイリンガルニュース', 'https://bilingualnews.jp/');
INSERT INTO Shownotes (episodeId, title, link) VALUES(111, 'ZOOM ズーム ハンディレコーダー H1n', 'https://www.amazon.co.jp/ZOOM-%E3%82%BA%E3%83%BC%E3%83%A0-H1n-%E3%83%8F%E3%83%B3%E3%83%87%E3%82%A3%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%80%E3%83%BC/dp/B077QFD4J6/?tag=bulknews-22');
INSERT INTO Shownotes (episodeId, title, link) VALUES(501, 'Heroku''s Ugly Secret', 'http://rapgenius.com/James-somers-herokus-ugly-secret-lyrics');
INSERT INTO Shownotes (episodeId, title, link) VALUES(501, 'Heroku Routing Performance Update', 'https://blog.heroku.com/archives/2013/2/16/routing_performance_update/');
INSERT INTO Shownotes (episodeId, title, link) VALUES(502, '5by5', 'http://5by5.tv');
INSERT INTO Shownotes (episodeId, title, link) VALUES(502, 'Mule Radio', 'http://www.muleradio.net');
INSERT INTO Shownotes (episodeId, title, link) VALUES(502, 'LTSV', 'http://ltsv.org');
INSERT INTO Shownotes (episodeId, title, link) VALUES(502, 'LTSV FAQ', 'http://d.hatena.ne.jp/naoya/20130209/1360381374');
INSERT INTO Shownotes (episodeId, title, link) VALUES(502, 'Perl 7', 'http://blogs.perl.org/users/ovid/2013/02/perl-7.html');
INSERT INTO Shownotes (episodeId, title, link) VALUES(502, 'Perl 7 Final thoughts', 'http://blogs.perl.org/users/ovid/2013/02/perl-7---final-thoughts.html');
