DROP TABLE IF EXISTS Episodes;

CREATE TABLE IF NOT EXISTS Episodes (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "title" TEXT NOT NULL,
  "link" TEXT NOT NULL,
  "pubDate" TEXT NOT NULL,
  "createdAt" INTEGER NOT NULL DEFAULT (unixepoch())
);

DROP TABLE IF EXISTS Shownotes;

CREATE TABLE IF NOT EXISTS Shownotes (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "episodeId" INTEGER NOT NULL,
  "title" TEXT NOT NULL,
  "link" TEXT NOT NULL,
  "createdAt" INTEGER NOT NULL DEFAULT (unixepoch())
);
